### ISSUE TITLE
Regression: Wrong Argument Count for Android writeFile

### ISSUE THREAD

**Issue by hhff** [itinance/react-native-fs#546]
It appears this recent commit has broken `writeFile` on android:
https://github.com/itinance/react-native-fs/pull/541/files

On Android, we're seeing:
```
RNFSManager.writeFile got 5 arguments, expected 4
```

I'd assume the fix that was made to add an argument to the iOS function signature also needs to be made to `RNFSManager.java`. I'd love to help, but my Java chops just aren't that strong I'm sorry!

**Comment by titoasty** [comment]
I just got this bug, seems pretty important cause even copyFile is broken

**Comment by modmido** [comment]
i got this bug too, after upgrading

**Comment by pistou** [comment]
Rolling back to `react-native-fs@2.11.15` is the temporary *"fix"* I used 😐

**Comment by itinance** [comment]
Its fixed with latest release

**Comment by itinance** [comment]
pls update to https://github.com/itinance/react-native-fs/tree/v2.11.17

**Comment by pistou** [comment]
I confirm `react-native-fs@2.11.17` fixed it

**Comment by Udbhav12** [comment]
Did any one manage to get it working ? I am using react-native-fs:2.12.1 and react-native: 0.57.7

I am still facing this problem

**Comment by itinance** [comment]
Have you tried to remove react-native-fs from node_modules directory and re-installing it?

**Comment by Udbhav12** [comment]
@itinance Yes i have tried it multiple times. Btw I am using  RNFS.DocumentDirectoryPath to write file inside a folder if it matters

**Comment by Udbhav12** [comment]
There was some cache issue,I cleared the cache and my problem is resolved now. Thanks anyhow
